updates to fix warnings for cleaner plans
mit-dci/terraform-aws-opencbdc-tctl pull request #20
Opened 2022-08-09 15:45 UTC by bvkin

2022-08-09 16:52 UTC, bvkin commented on modules/vpc-endpoints/terraform.tf
> +terraform {
fixes:
> │ Warning: Reference to undefined provider
│ 
│   on main.tf line 256, in module "vpc_endpoints_use1":
│  256:     aws = aws.use1

2022-08-09 16:53 UTC, bvkin commented on main.tf
> -  server_side_encryption_configuration {
Fixes:
> │ Warning: Argument is deprecated
│ 
│   with aws_s3_bucket.binaries,
│   on main.tf line 442, in resource "aws_s3_bucket" "binaries":
│  442: resource "aws_s3_bucket" "binaries" {

2022-08-09 16:56 UTC, bvkin commented on modules/test-controller-deploy/main.tf
> +resource "aws_codestarconnections_connection" "this" {
Will require a login to codepipeline from the console
Fixes
> Fixes
Warning: The CodePipeline GitHub version 1 action provider is deprecated.

2022-08-09 16:57 UTC, bvkin commented on outputs.tf
> +        opensearch_endpoint = var.create_opensearch ? module.opensearch[0].opensearch_endpoint : ""
Allows a plan in an un-initialized environment to finish

2022-08-09 17:04 UTC, jallen-frb approved these changes

2022-08-11 15:57 UTC, jallen-frb approved these changes

2022-08-11 16:00 UTC, kylecrawshaw requested changes
Please sign commits to pass DCO.

2022-08-11 17:19 UTC, kylecrawshaw approved these changes
LGTM

2022-08-11 17:22 UTC, merged